/**
 * Codegen — consumes a `ClientManifest` (from @usehyper/core) and emits a
 * pair of files:
 *
 *   client.ts       — a runtime proxy wrapping fetchTransport
 *   client.d.ts     — compile-time types for every route
 *
 * This is the moral equivalent of tRPC's router typings, minus reflection.
 *
 * Live-watch integration (hyper dev) is added in the CLI; this module stays
 * a pure function so it can be called from tests and from build pipelines.
 */

import type { ClientManifest } from "@usehyper/core"

export interface CodegenOptions {
  readonly manifest: ClientManifest
  /** Default baseUrl embedded in the emitted file (overridable at runtime). */
  readonly baseUrl?: string
  /** Name for the generated root client (defaults to "api"). */
  readonly rootName?: string
  /**
   * Emit `Result<T, Errors>` tagged-union leaf signatures alongside the
   * exception-throwing leaves. Off by default for minimum-diff ergonomics;
   * apps that prefer explicit error handling should opt in.
   */
  readonly resultTypes?: boolean
}

export function generateClient(opts: CodegenOptions): {
  runtime: string
  declaration: string
} {
  const root = opts.rootName ?? "api"
  const resultTypes = opts.resultTypes ?? false
  const tree = buildTree(opts.manifest.routes)
  const dts = emitDts(tree, root, resultTypes)
  const js = emitRuntime(tree, root, opts.baseUrl, resultTypes)
  return { runtime: js, declaration: dts }
}

// --- path-to-namespace tree --------------------------------------------------

interface Leaf {
  readonly kind: "leaf"
  readonly method: string
  readonly path: string
  readonly name: string
  readonly errors?: readonly string[]
  readonly throws?: readonly number[]
}
interface Branch {
  readonly kind: "branch"
  readonly children: Map<string, Leaf | Branch>
}

type Node = Leaf | Branch

function buildTree(routes: readonly ClientManifest["routes"][number][]): Branch {
  const root: Branch = { kind: "branch", children: new Map() }
  for (const r of routes) {
    const name = r.name ?? defaultName(r.method, r.path)
    const segments = splitName(name)
    let cur: Branch = root
    for (let i = 0; i < segments.length - 1; i++) {
      const seg = segments[i]!
      let next = cur.children.get(seg)
      if (!next || next.kind !== "branch") {
        next = { kind: "branch", children: new Map() }
        cur.children.set(seg, next)
      }
      cur = next
    }
    cur.children.set(segments[segments.length - 1]!, {
      kind: "leaf",
      method: r.method,
      path: r.path,
      name,
      ...(r.errors && r.errors.length > 0 && { errors: r.errors }),
      ...(r.throws && r.throws.length > 0 && { throws: r.throws }),
    })
  }
  return root
}

function splitName(name: string): string[] {
  return name
    .replace(/[^A-Za-z0-9._]+/g, "_")
    .split(/[._]/)
    .filter((s) => s.length > 0)
}

function defaultName(method: string, path: string): string {
  return `${method.toLowerCase()}_${path.replace(/[^A-Za-z0-9]+/g, "_")}`
}

// --- emitters ---------------------------------------------------------------

function emitRuntime(
  root: Branch,
  rootName: string,
  baseUrl: string | undefined,
  resultTypes: boolean,
): string {
  const leafHelper = resultTypes
    ? `const leaf = (method, path) => async (input = {}) => {\n    try {\n      return { ok: true, value: await client.call({ method, path, ...input }) }\n    } catch (e) {\n      return { ok: false, error: { code: e.code ?? "unknown", status: e.status ?? 500, message: e.message ?? String(e) } }\n    }\n  }`
    : "const leaf = (method, path) => (input = {}) => client.call({ method, path, ...input })"
  const header = `/* eslint-disable */\n/* Generated by @usehyper/client/codegen. Do not edit. */\nimport { createClient } from "@usehyper/client"\nimport { fetchTransport } from "@usehyper/client"\n\nexport function build(opts = {}) {\n  const transport = opts.transport ?? fetchTransport({ baseUrl: opts.baseUrl ?? ${JSON.stringify(baseUrl ?? "")}, headers: opts.headers })\n  const client = createClient(transport)\n  ${leafHelper}\n  return ${runtimeLiteral(root)}\n}\n\nexport const ${rootName} = build()\n`
  return header
}

function runtimeLiteral(node: Node): string {
  if (node.kind === "leaf")
    return `leaf(${JSON.stringify(node.method)}, ${JSON.stringify(node.path)})`
  const entries: string[] = []
  for (const [k, child] of node.children) {
    entries.push(`  ${safeKey(k)}: ${runtimeLiteral(child)}`)
  }
  return `{\n${entries.join(",\n")}\n}`
}

function emitDts(root: Branch, rootName: string, resultTypes: boolean): string {
  const preamble = resultTypes
    ? `export type Ok<T> = { readonly ok: true; readonly value: T }\nexport type Err<C extends string> = { readonly ok: false; readonly error: { readonly code: C; readonly status: number; readonly message: string } }\nexport type Result<T, C extends string> = Ok<T> | Err<C>\nexport type Leaf<T = unknown, C extends string = "unknown"> = (input?: Input) => Promise<Result<T, C>>\n`
    : "export type Leaf<T = unknown> = (input?: Input) => Promise<T>\n"
  const header = `/* Generated by @usehyper/client/codegen. Do not edit. */\nimport type { Transport } from "@usehyper/client"\n\nexport type Input = {\n  params?: Record<string, string>\n  query?: Record<string, unknown>\n  body?: unknown\n  headers?: Record<string, string>\n  signal?: AbortSignal\n}\n\n${preamble}\nexport type Client = ${dtsLiteral(root, 0, resultTypes)}\n\nexport const ${rootName}: Client\nexport function build(opts?: { baseUrl?: string; headers?: Record<string, string>; transport?: Transport }): Client\n`
  return header
}

function dtsLiteral(node: Node, indent: number, resultTypes: boolean): string {
  if (node.kind === "leaf") {
    if (!resultTypes) return "Leaf"
    const codes = [...(node.errors ?? []), ...(node.throws ?? []).map((n) => `http_${n}`)]
    if (codes.length === 0) return "Leaf"
    const union = codes.map((c) => JSON.stringify(c)).join(" | ")
    return `Leaf<unknown, ${union}>`
  }
  const pad = "  ".repeat(indent + 1)
  const entries: string[] = []
  for (const [k, child] of node.children) {
    entries.push(`${pad}${safeKey(k)}: ${dtsLiteral(child, indent + 1, resultTypes)}`)
  }
  return `{\n${entries.join("\n")}\n${"  ".repeat(indent)}}`
}

function safeKey(k: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k)
}
