/**
 * Registry client.
 *
 * Resolution order:
 *   1. fetch `<registryUrl>/r/<name>(@<version>)?.json`
 *   2. on network failure or non-200, fall back to the bundled snapshot
 *      (regenerated by the root `postinstall` and the CLI's `prepack` hook)
 *   3. on no match, throw
 *
 * The bundled snapshot keeps `hyper add` working in air-gapped CI and during
 * registry outages. It's meant as a safety net, not a primary path — production
 * installs always hit the network when reachable.
 *
 * The snapshot is loaded lazily because it's gitignored: in a fresh clone
 * before `postinstall` runs, the file may not exist. That's fine — we just
 * skip the fallback in that case.
 */

import type { RegistryComponent, RegistryIndex } from "./types.ts"

interface Snapshot {
  readonly index: RegistryIndex
  readonly components: Readonly<Record<string, RegistryComponent>>
}

let snapshotCache: Snapshot | null | undefined

async function loadSnapshot(): Promise<Snapshot | null> {
  if (snapshotCache !== undefined) return snapshotCache
  try {
    const mod = (await import("./snapshot.ts")) as {
      SNAPSHOT_INDEX: RegistryIndex
      SNAPSHOT_COMPONENTS: Readonly<Record<string, RegistryComponent>>
    }
    snapshotCache = { index: mod.SNAPSHOT_INDEX, components: mod.SNAPSHOT_COMPONENTS }
  } catch {
    snapshotCache = null
  }
  return snapshotCache
}

export interface RegistryClient {
  readonly url: string
  getIndex(): Promise<RegistryIndex>
  getComponent(name: string, version?: string): Promise<RegistryComponent>
  listComponents(): Promise<
    readonly { name: string; version: string; title?: string; description: string }[]
  >
}

export interface RegistryClientOptions {
  readonly url?: string
  /** Force snapshot-only mode (offline, deterministic CI). */
  readonly offline?: boolean
  /** Throw on snapshot fallback (used by tests + strict CI). */
  readonly noFallback?: boolean
  /** Override fetch for tests. */
  readonly fetch?: typeof fetch
}

const DEFAULT_URL = "https://hyperjs.ai"

export class RegistryError extends Error {
  override readonly name = "RegistryError"
  constructor(
    message: string,
    readonly status?: number,
  ) {
    super(message)
  }
}

export function createRegistryClient(opts: RegistryClientOptions = {}): RegistryClient {
  const url = (opts.url ?? DEFAULT_URL).replace(/\/+$/, "")
  const offline = opts.offline === true
  const noFallback = opts.noFallback === true
  const fetchFn = opts.fetch ?? globalThis.fetch

  const tryFetch = async <T>(path: string): Promise<T | null> => {
    if (offline) return null
    try {
      const res = await fetchFn(`${url}${path}`, {
        headers: { accept: "application/json" },
      })
      if (!res.ok) return null
      return (await res.json()) as T
    } catch {
      return null
    }
  }

  return {
    url,
    async getIndex() {
      const remote = await tryFetch<RegistryIndex>("/r/index.json")
      if (remote) return remote
      if (noFallback) throw new RegistryError(`failed to fetch ${url}/r/index.json`)
      const snap = await loadSnapshot()
      if (!snap) throw new RegistryError("registry unreachable and no offline snapshot available")
      return snap.index
    },
    async getComponent(name, version) {
      const slug = version ? `${name}@${version}` : name
      const remote = await tryFetch<RegistryComponent>(`/r/${slug}.json`)
      if (remote) return remote
      const snap = await loadSnapshot()
      const cached = snap?.components[name]
      if (!cached) throw new RegistryError(`component not found: ${name}`)
      if (version && cached.version !== version) {
        throw new RegistryError(
          `version mismatch (snapshot has ${cached.version}, requested ${version})`,
        )
      }
      if (noFallback) throw new RegistryError(`failed to fetch ${url}/r/${slug}.json`)
      return cached
    },
    async listComponents() {
      const idx = await this.getIndex()
      return idx.components.map((c) => ({
        name: c.name,
        version: c.version,
        description: c.description,
        ...(c.title !== undefined && { title: c.title }),
      }))
    },
  }
}
