#!/usr/bin/env bun
/**
 * Bootstraps registry components for every example in `apps/examples/*`
 * that uses the registry workflow (i.e. has a `hyper.config.json` +
 * `hyper.lock.json`).
 *
 * Why centralize this in the repo-root `postinstall` instead of having each
 * example run its own postinstall hook?
 *
 *   1. `apps/examples/*` are gitignored at `src/hyper/` — the components
 *      need to land somewhere. They have to be regenerated on every fresh
 *      clone.
 *   2. The CLI's offline snapshot fallback (`packages/cli/src/registry/
 *      snapshot.ts`) is generated by `tools/build-snapshots.ts`, which runs
 *      first in the root `postinstall`. Only AFTER that does the CLI have
 *      something to fall back to when offline. Per-example `postinstall`
 *      hooks would race against that.
 *   3. Workspace symlinks are already in place by the time the root
 *      `postinstall` runs, so `packages/cli/src/bin.ts` is invokable.
 *
 * Idempotent: skips examples whose `src/hyper/<component>` already exists
 * (the `hyper add` applier will warn on a hash mismatch — `--force` is left
 * off intentionally so local edits aren't blasted away).
 */

import { spawn } from "node:child_process"
import { readdir, stat } from "node:fs/promises"
import { join, resolve } from "node:path"

const ROOT = resolve(import.meta.dir, "..")
const EXAMPLES = join(ROOT, "apps/examples")
const CLI = join(ROOT, "packages/cli/src/bin.ts")

interface LockShape {
  components?: Record<string, unknown>
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await stat(p)
    return true
  } catch {
    return false
  }
}

async function bootstrap(dir: string): Promise<void> {
  const config = join(dir, "hyper.config.json")
  const lock = join(dir, "hyper.lock.json")
  if (!(await pathExists(config)) || !(await pathExists(lock))) return

  const lockText = await Bun.file(lock).text()
  let components: string[]
  try {
    const parsed = JSON.parse(lockText) as LockShape
    components = Object.keys(parsed.components ?? {})
  } catch {
    return
  }
  if (components.length === 0) return

  // Skip if every component is already present — keeps repeat installs fast
  // and preserves any local edits the dev has made.
  const missing: string[] = []
  for (const c of components) {
    if (!(await pathExists(join(dir, "src/hyper", c)))) missing.push(c)
  }
  if (missing.length === 0) return

  process.stdout.write(`bootstrapping ${dir} (${missing.join(", ")})…\n`)
  await new Promise<void>((res, rej) => {
    const child = spawn("bun", [CLI, "add", ...missing], { cwd: dir, stdio: "inherit" })
    child.on("error", rej)
    child.on("exit", (code) => {
      if (code !== 0) rej(new Error(`hyper add exited ${code} in ${dir}`))
      else res()
    })
  })
}

async function main(): Promise<number> {
  if (!(await pathExists(EXAMPLES))) return 0
  const entries = await readdir(EXAMPLES, { withFileTypes: true })
  for (const e of entries) {
    if (!e.isDirectory()) continue
    try {
      await bootstrap(join(EXAMPLES, e.name))
    } catch (err) {
      console.error(`warning: ${e.name} bootstrap failed — ${(err as Error).message}`)
    }
  }
  return 0
}

main().then((code) => process.exit(code))
