#!/usr/bin/env bun
/**
 * Snapshot writer.
 *
 * Builds the registry once and bakes the result into two TypeScript modules
 * that ship with the consumers that need them:
 *
 *   - packages/cli/src/registry/snapshot.ts        — CLI offline fallback
 *   - apps/website/lib/registry-data.ts            — Next.js registry routes
 *
 * Neither file is committed to git. They're regenerated by:
 *
 *   - the root `postinstall` script after every `bun install`
 *   - the CLI's `prepack` hook before publishing to npm
 *   - the website's `vercel-build` hook at deploy time
 *
 * Idempotent — rewrites both files even if contents are identical.
 */

import { mkdir, writeFile } from "node:fs/promises"
import { dirname, relative, resolve } from "node:path"
import { buildAll, buildIndex, validate } from "./registry/build.ts"

const ROOT = resolve(import.meta.dir, "..")
const CLI_OUT = resolve(ROOT, "packages/cli/src/registry/snapshot.ts")
const WEBSITE_OUT = resolve(ROOT, "apps/website/lib/registry-data.ts")

const BANNER =
  "/**\n * Auto-generated by tools/build-snapshots.ts. Do not edit.\n *\n" +
  " * Bundled snapshot of the registry, regenerated on every install + deploy.\n */"

async function writeFileAtomic(path: string, body: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, body)
}

async function main(): Promise<number> {
  const components = await buildAll()
  if (components.length === 0) {
    console.error("error: no components found")
    return 1
  }
  const issues = validate(components)
  for (const issue of issues) {
    if (issue.kind === "missing-dep") {
      console.error(`error: ${issue.message}`)
    } else {
      console.warn(`warning: ${issue.message}`)
    }
  }
  if (issues.some((i) => i.kind === "missing-dep")) return 1

  const index = buildIndex(components)
  const indexJson = JSON.stringify(index, null, 2)
  const componentsJson = JSON.stringify(
    Object.fromEntries(components.map((c) => [c.name, c])),
    null,
    2,
  )

  const cliBody = [
    BANNER,
    "",
    `import type { RegistryComponent, RegistryIndex } from "./types.ts"`,
    "",
    `export const SNAPSHOT_INDEX: RegistryIndex = ${indexJson} as const`,
    "",
    `export const SNAPSHOT_COMPONENTS: Readonly<Record<string, RegistryComponent>> = ${componentsJson} as const`,
    "",
  ].join("\n")
  await writeFileAtomic(CLI_OUT, cliBody)

  const websiteBody = [
    BANNER,
    "",
    "import type {",
    "  RegistryComponent,",
    "  RegistryIndex,",
    '} from "../../../tools/registry-types.ts"',
    "",
    `export const REGISTRY_INDEX: RegistryIndex = ${indexJson} as const`,
    "",
    `export const REGISTRY_COMPONENTS: Readonly<Record<string, RegistryComponent>> = ${componentsJson} as const`,
    "",
  ].join("\n")
  await writeFileAtomic(WEBSITE_OUT, websiteBody)

  console.log(
    `wrote ${relative(ROOT, CLI_OUT)} + ${relative(ROOT, WEBSITE_OUT)} (${components.length} components)`,
  )
  return 0
}

main().then((code) => {
  process.exit(code)
})
