/**
 * Manifest source for the registry service.
 *
 * Manifests are not checked into the repo. Two paths feed this module:
 *
 *   1. Bundled snapshot — `./generated/registry-data.ts`, regenerated by the
 *      root `postinstall` and the registry's `vercel-build` hook. This is the
 *      production path: the data ships inside the function bundle, so no fs
 *      walk runs at request time.
 *
 *   2. Live build — `tools/registry/build.ts` walking `packages/*` directly.
 *      Used as a fallback in fresh clones and during local dev when the
 *      generated file is missing or stale.
 *
 * Both paths produce identical shapes; the snapshot is just a pre-flattened
 * cache.
 *
 * The result is held in a process-local promise so every request shares one
 * build. Vercel spins fresh function instances on deploy, which is exactly
 * when we want the build to re-run.
 */

import type { RegistryComponent, RegistryIndex } from "../../../tools/registry-types.ts"

export type Manifest = RegistryComponent
export type ManifestFile = RegistryComponent["files"][number]
export type IndexEntry = RegistryIndex["components"][number]
export type Index = RegistryIndex

export interface RegistrySnapshot {
  readonly index: Index
  readonly components: readonly RegistryComponent[]
  readonly byName: ReadonlyMap<string, RegistryComponent>
}

let snapshotPromise: Promise<RegistrySnapshot> | null = null

async function loadFromGenerated(): Promise<RegistrySnapshot | null> {
  try {
    const mod = (await import("./generated/registry-data.ts")) as {
      REGISTRY_INDEX: RegistryIndex
      REGISTRY_COMPONENTS: Readonly<Record<string, RegistryComponent>>
    }
    const components = Object.values(mod.REGISTRY_COMPONENTS)
    const byName = new Map<string, RegistryComponent>()
    for (const c of components) byName.set(c.name, c)
    return { index: mod.REGISTRY_INDEX, components, byName }
  } catch {
    return null
  }
}

async function loadFromSource(): Promise<RegistrySnapshot> {
  const { buildAll, buildIndex } = await import("../../../tools/registry/build.ts")
  const components = await buildAll()
  const index = buildIndex(components)
  const byName = new Map<string, RegistryComponent>()
  for (const c of components) byName.set(c.name, c)
  return { index, components, byName }
}

async function build(): Promise<RegistrySnapshot> {
  return (await loadFromGenerated()) ?? (await loadFromSource())
}

export function loadManifests(): Promise<RegistrySnapshot> {
  if (!snapshotPromise) snapshotPromise = build()
  return snapshotPromise
}

export function resetCache(): void {
  snapshotPromise = null
}
